image: ringcentral/maven:3.6.3-jdk11.0.7
pipelines:
  branches:
    master:
        - step:
            caches:
              - maven
            script:
              - apk add --no-cache openssl gnupg
              - openssl aes-256-cbc -pass pass:$GPG_PWD -in bitbucket-pipelines.gpg.enc -out bitbucket-pipelines.gpg -d -md md5
              - gpg --import bitbucket-pipelines.gpg
              - mvn -V -B -s bitbucket-pipelines.xml deploy
    develop:
        - step:
            caches:
              - maven
            script:
              - apk add --no-cache openssl gnupg
              - openssl aes-256-cbc -pass pass:$GPG_PWD -in bitbucket-pipelines.gpg.enc -out bitbucket-pipelines.gpg -d -md md5
              - gpg --import bitbucket-pipelines.gpg
              - mvn -V -B -U -s bitbucket-pipelines.xml deploy
  default:
    - step:
        caches:
          - maven
        script:
          - mvn -V -B -U install -Dgpg.skip