/**
 * The GOAL Grammar Tools. Copyright (C) 2014 Koen Hindriks.
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <http://www.gnu.org/licenses/>.
 */

package languageTools.program.kr;

import java.util.Collections;
import java.util.List;

import krTools.language.DatabaseFormula;
import krTools.language.Query;
import krTools.parser.SourceInfo;
import languageTools.analyzer.FileRegistry;
import languageTools.program.Program;

/**
 * Generic interface for all types of programs, i.e., MAS programs, agent
 * programs, modules, and tests, that may be generated by the GOAL Grammar
 * Tools.
 */
public class KRProgram extends Program {
	private final List<DatabaseFormula> formulas;
	private final List<Query> queries;

	public KRProgram(FileRegistry registry, List<DatabaseFormula> formulas, List<Query> queries, SourceInfo info) {
		super(registry, info);
		this.formulas = formulas;
		this.queries = queries;
	}

	public List<DatabaseFormula> getDBFormulas() {
		return Collections.unmodifiableList(this.formulas);
	}

	public List<Query> getQueries() {
		return Collections.unmodifiableList(this.queries);
	}

	@Override
	public String toString() {
		// TODO
		return "";
	}
}
